# Based on the instructions from https://mojo.redhat.com/docs/DOC-1060392
- hosts: all
  become: yes
  tasks:
    - name: Fix Red Hat DNS server
      lineinfile: dest=/etc/resolv.conf regexp=^nameserver line='nameserver 10.38.5.26'

    - name: Prevent DNS lookup by SSH
      lineinfile: dest=/etc/ssh/sshd_config regexp=^UseDNS line='UseDNS no'
      notify:
        - restart sshd

    - name: Add the RHSC-2.0-Agent repo to the machine
      command: yum-config-manager --add http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/rhscon-2-rhel-7-compose/latest-RHSCON-2-RHEL-7/compose/Agent/x86_64/os/
      args:
        creates: /etc/yum.repos.d/download.eng.bos.redhat.com_rcm-guest_ceph-drops_auto_rhscon-2-rhel-7-compose_latest-RHSCON-2-RHEL-7_compose_Agent_x86_64_os_.repo

    - name: Add the RHSC-2.0-Installer repo to the machine
      command: yum-config-manager --add http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/rhscon-2-rhel-7-compose/latest-RHSCON-2-RHEL-7/compose/Installer/x86_64/os/
      args:
        creates: /etc/yum.repos.d/download.eng.bos.redhat.com_rcm-guest_ceph-drops_auto_rhscon-2-rhel-7-compose_latest-RHSCON-2-RHEL-7_compose_Installer_x86_64_os_.repo

    - name: Add the RHSC-2.0-Main repo to the machine
      command: yum-config-manager --add http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/rhscon-2-rhel-7-compose/latest-RHSCON-2-RHEL-7/compose/Main/x86_64/os/
      args:
        creates: /etc/yum.repos.d/download.eng.bos.redhat.com_rcm-guest_ceph-drops_auto_rhscon-2-rhel-7-compose_latest-RHSCON-2-RHEL-7_compose_Main_x86_64_os_.repo

    - name: Add CEPH-2.0-MON repo
      command: yum-config-manager --add http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/ceph-2-rhel-7-compose/latest-Ceph-2-RHEL-7/compose/MON/x86_64/os/
      args:
        creates: /etc/yum.repos.d/download.eng.bos.redhat.com_rcm-guest_ceph-drops_auto_ceph-2-rhel-7-compose_latest-Ceph-2-RHEL-7_compose_MON_x86_64_os_.repo

    - name: Add CEPH-2.0-OSD repo
      command: yum-config-manager --add http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/ceph-2-rhel-7-compose/latest-Ceph-2-RHEL-7/compose/OSD/x86_64/os/
      args:
        creates: /etc/yum.repos.d/download.eng.bos.redhat.com_rcm-guest_ceph-drops_auto_ceph-2-rhel-7-compose_latest-Ceph-2-RHEL-7_compose_OSD_x86_64_os_.repo

    - name: Add CEPH-2.0-Tools repo
      command: yum-config-manager --add http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/ceph-2-rhel-7-compose/latest-Ceph-2-RHEL-7/compose/Tools/x86_64/os/
      args:
        creates: /etc/yum.repos.d/download.eng.bos.redhat.com_rcm-guest_ceph-drops_auto_ceph-2-rhel-7-compose_latest-Ceph-2-RHEL-7_compose_Tools_x86_64_os_.repo

    # - name: Install salt repo
    #   yum: name=https://repo.saltstack.com/yum/redhat/salt-repo-latest-1.el7.noarch.rpm disable_gpg_check=yes

    - name: Disable gpgcheck in yum.conf globally
      lineinfile: dest=/etc/yum.conf regexp=^gpgcheck= line=gpgcheck=0

    - name: Prevent ansible from creating retry files
      lineinfile: dest=/etc/ansible/ansible.cfg regexp=#retry_files_enabled line='retry_files_enabled = False'

    # - name: Downgrade ansible (for RHSCON)
    #   command: yum downgrade ansible-1.9.4 -y 

    - name: Install ceph-installer dependencies except ansible
      shell: for i in `yum deplist ceph-installer | grep provider | grep -v ansible | awk -e '{print $2}'`; do yum install -y $i; done

    - name: Get latest ceph-installer rpm package
      shell: wget $(yum list ceph-installer | grep ceph-installer | sed 's/.noarch//' | awk -e '{print "http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/rhscon-2-rhel-7-compose/latest-RHSCON-2-RHEL-7/compose/Installer/x86_64/os/Packages/" $1 "-" $2 ".noarch.rpm"}')  -O /tmp/ceph-installer.rpm

    - name: Cheat the system and install ceph-installer with newer ansible (ignoring all dependencies)
      command: rpm -Uvh --nodeps /tmp/ceph-installer.rpm
      ignore_errors: yes # will error mostly due to the fact that the thing is already installed...

    - name: Get latest ceph-ansible rpm package
      shell: wget $(yum list ceph-ansible | grep ceph-ansible | sed 's/.noarch//' | awk -e '{print "http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/rhscon-2-rhel-7-compose/latest-RHSCON-2-RHEL-7/compose/Installer/x86_64/os/Packages/" $1 "-" $2 ".noarch.rpm"}')  -O /tmp/ceph-ansible.rpm

    - name: Cheat the system and install ceph-ansible with newer ansible (ignoring all dependencies)
      command: rpm -Uvh --nodeps /tmp/ceph-ansible.rpm
      ignore_errors: yes # will error mostly due to the fact that the thing is already installed...

    - name: Install rhscon packages
      yum: name={{ item }} disable_gpg_check=yes
      with_items:
        - rhscon-core
        - rhscon-ceph
        - rhscon-ui

    - name: Install python-pip (necessary for pexpect)
      yum: name=python-pip disable_gpg_check=yes enablerepo=epel

    - name: Install pexpect (dependency for ansible expect later on)
      pip: name=pexpect

    - name: Update the configuration file to update ceph-installer flags
      lineinfile: dest=/etc/skyring/providers.d/ceph.conf regexp=redhatstorage line='        "redhatstorage":false,'

    - name: Update the configuration file to update ceph-installer flags
      lineinfile: dest=/etc/skyring/providers.d/ceph.conf regexp=redhatusecdn line='        "redhatusecdn":false'

# Removed because of https://bugzilla.redhat.com/show_bug.cgi?id=1354102
# To allow for 1 MON clusters you need to modify min_monitors_in_cluster in /etc/skyring/providers.d/ceph.conf additionally
    # - name: Edit the UI configuration for allowing cluster creation with single MON
    #   lineinfile: "dest=/usr/share/skyring/webapp/config/config.json regexp=ceph_min_monitors line='    \"ceph_min_monitors\": 1,'"

    - name: Run the following script to setup skyring
      expect:
        command: skyring-setup
        responses:
          (?i)Would you like to create one now?: "yes"
          (?i)Username: ""
          (?i)Email: ""
          (?i)Password: "redhat"
          # (?i)Do you wish: "N" # Configure for HTTP
          (?i)Do you wish: "Y" # Configure for HTTPS
          (?i)Enter pass phrase: "redhat"
          (?i)Verifying: "redhat"
          (?i)Country: ""
          (?i)State: ""
          (?i)Locality: ""
          (?i)Organization: ""
          (?i)Organizational: ""
          (?i)Common: ""
          (?i)A challenge password: ""
          (?i)An optional company name: ""
          (?i)Please enter the FQDN of server: ""

    - template: src=/vagrant/ansible-rhsc-pre-requirements.yml dest=/usr/share/ceph-ansible/roles/ceph-agent/tasks/pre_requisite.yml owner=root group=root mode=0644

    # - name: Fix dashboard collectd issues BZ 1339979
    #   replace: dest=/srv/salt/collectd/files/collectd.conf regexp='fqdn' replace='id'


    - name: Restart skyring to reload changes in collectd template
      service: name=skyring state=restarted


  handlers:
    - name: restart sshd
      service: name=sshd state=restarted