# Based on the instructions from https://mojo.redhat.com/docs/DOC-1060392
- hosts: all
  become: yes
  tasks:
    - name: Fix Red Hat DNS server
      lineinfile: dest=/etc/resolv.conf regexp=^nameserver line='nameserver 10.38.5.26'

    - name: Prevent DNS lookup by SSH
      lineinfile: dest=/etc/ssh/sshd_config regexp=^UseDNS line='UseDNS no'
      notify:
        - restart sshd

    - name: Disable gpgcheck in yum.conf globally
      lineinfile: dest=/etc/yum.conf regexp=^gpgcheck= line=gpgcheck=0

    - name: Prevent ansible from creating retry files
      lineinfile: dest=/etc/ansible/ansible.cfg regexp=#retry_files_enabled line='retry_files_enabled = False'

    - name: Add the RHSC-2.0-Agent repo to the machine
      command: yum-config-manager --add http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/rhscon-2-rhel-7-compose/latest-RHSCON-2-RHEL-7/compose/Agent/x86_64/os/
      args:
        creates: /etc/yum.repos.d/download.eng.bos.redhat.com_rcm-guest_ceph-drops_auto_rhscon-2-rhel-7-compose_latest-RHSCON-2-RHEL-7_compose_Agent_x86_64_os_.repo

    - name: Add the RHSC-2.0-Installer repo to the machine
      command: yum-config-manager --add http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/rhscon-2-rhel-7-compose/latest-RHSCON-2-RHEL-7/compose/Installer/x86_64/os/
      args:
        creates: /etc/yum.repos.d/download.eng.bos.redhat.com_rcm-guest_ceph-drops_auto_rhscon-2-rhel-7-compose_latest-RHSCON-2-RHEL-7_compose_Installer_x86_64_os_.repo

    - name: Add the RHSC-2.0-Main repo to the machine
      command: yum-config-manager --add http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/rhscon-2-rhel-7-compose/latest-RHSCON-2-RHEL-7/compose/Main/x86_64/os/
      args:
        creates: /etc/yum.repos.d/download.eng.bos.redhat.com_rcm-guest_ceph-drops_auto_rhscon-2-rhel-7-compose_latest-RHSCON-2-RHEL-7_compose_Main_x86_64_os_.repo

    - name: Add CEPH-2.0-MON repo
      command: yum-config-manager --add http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/ceph-2-rhel-7-compose/latest-Ceph-2-RHEL-7/compose/MON/x86_64/os/
      args:
        creates: /etc/yum.repos.d/download.eng.bos.redhat.com_rcm-guest_ceph-drops_auto_ceph-2-rhel-7-compose_latest-Ceph-2-RHEL-7_compose_MON_x86_64_os_.repo

    - name: Add CEPH-2.0-OSD repo
      command: yum-config-manager --add http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/ceph-2-rhel-7-compose/latest-Ceph-2-RHEL-7/compose/OSD/x86_64/os/
      args:
        creates: /etc/yum.repos.d/download.eng.bos.redhat.com_rcm-guest_ceph-drops_auto_ceph-2-rhel-7-compose_latest-Ceph-2-RHEL-7_compose_OSD_x86_64_os_.repo

    - name: Add CEPH-2.0-Tools repo
      command: yum-config-manager --add http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/ceph-2-rhel-7-compose/latest-Ceph-2-RHEL-7/compose/Tools/x86_64/os/
      args:
        creates: /etc/yum.repos.d/download.eng.bos.redhat.com_rcm-guest_ceph-drops_auto_ceph-2-rhel-7-compose_latest-Ceph-2-RHEL-7_compose_Tools_x86_64_os_.repo

    - name: Add the RHEL extra repo
      command: yum-config-manager --add http://download.eng.bos.redhat.com/rel-eng/updates/latest-EXTRAS-7-RHEL-7/compose/Server/x86_64/os
      # args:
        # creates: /etc/yum.repos.d/rhscon.repo

    # - name: Install salt repo
    #   yum: name=https://repo.saltstack.com/yum/redhat/salt-repo-latest-1.el7.noarch.rpm disable_gpg_check=yes

    - name: Remove current machine-id
      file: path=/etc/machine-id state=absent

    - name: Regenerate new randome machine-id
      command: systemd-machine-id-setup

    - name: Install ceph-installer dependencies except ansible
      shell: for i in `yum deplist ceph-installer | grep provider | grep -v ansible | awk -e '{print $2}'`; do yum install -y $i; done

    - name: Get latest ceph-installer rpm package
      shell: wget $(yum list ceph-installer | grep ceph-installer | sed 's/.noarch//' | awk -e '{print "http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/rhscon-2-rhel-7-compose/latest-RHSCON-2-RHEL-7/compose/Installer/x86_64/os/Packages/" $1 "-" $2 ".noarch.rpm"}')  -O /tmp/ceph-installer.rpm

    - name: Cheat the system and install ceph-installer with newer ansible (ignoring all dependencies)
      command: rpm -Uvh --nodeps /tmp/ceph-installer.rpm
      ignore_errors: yes # will error mostly due to the fact that the thing is already installed...

    - name: Get latest ceph-ansible rpm package
      shell: wget $(yum list ceph-ansible | grep ceph-ansible | sed 's/.noarch//' | awk -e '{print "http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/auto/rhscon-2-rhel-7-compose/latest-RHSCON-2-RHEL-7/compose/Installer/x86_64/os/Packages/" $1 "-" $2 ".noarch.rpm"}')  -O /tmp/ceph-ansible.rpm

    - name: Cheat the system and install ceph-ansible with newer ansible (ignoring all dependencies)
      command: rpm -Uvh --nodeps /tmp/ceph-ansible.rpm
      ignore_errors: yes # will error mostly due to the fact that the thing is already installed...

    - name: Manually place the ssh authorized key in the new location
      get_url: url="http://RHS-C:8181/setup/key/" dest=/var/lib/ceph-installer/.ssh/authorized_keys owner=ceph-installer mode=0600

    - name: Setup ansible handshake with ceph-installer
      command: bash -c "curl http://RHS-C:8181/setup/ | bash"

    - name: Install the rhscon-agent packages
      command: bash -c "curl http://RHS-C:8181/setup/agent/ | bash"
      register: install_code

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted

    # - uri:
    #   url: http://RHS-C:8181/api/tasks/9c5c1771-d86a-4fe1-b596-2033a6914ac9/
    #   method: GET
    #   return_content: yes
