---

- name: install ansible docker prerequisites
  yum: name=docker-python state=present

- name: install docker and container-storage-setup
  yum: name={{ item }} state=present
  with_items:
    - docker
    - container-storage-setup

- name: create docker storage config
  copy: src=docker-storage-setup-rhel-7 dest=/etc/sysconfig/docker-storage-setup

- name: start docker
  service: name=docker state=started enabled=yes

...
