---

- name: install docker
  yum: name=docker state=present

- name: create docker storage config
  copy: src=docker-storage-setup-rhel-7 dest=/etc/sysconfig/docker-storage-setup

- name: start docker
  service: name=docker state=started enabled=yes

...
