---

- name: install ceph-ansible-copilot pre-requisites
  yum: name={{ item }} state=present
  with_items:
    - git
    - python-urwid
    - python-paramiko

- name: checkout ceph-ansible-copilot from GitHub
  git:
    repo: https://github.com/pcuzner/ceph-ansible-copilot.git
    dest: /home/vagrant/ceph-ansible-copilot
    force: yes
  become: false

- name: install ceph-ansible-copilot via setup.py
  shell: python setup.py install
  args:
    chdir: /home/vagrant/ceph-ansible-copilot

- name: manage root ssh keys
  user:
    name: root
    generate_ssh_key: yes
  register: root_id_rsa

- name: install root public key as authorized_key for root user
  authorized_key:
    user: root
    key: "{{ root_id_rsa.ssh_public_key }}"

...
