---

- name: pre-downloading rhcs packages
  shell: yum -y --downloadonly --resolve install {{ item }}
  args:
    warn: no
  with_items:
    - ceph-base
    - ceph-common
    - ceph-selinux
    - ceph-osd
    - ceph-mon
    - ceph-mgr
    - cephmetrics-collectors
    - ceph-fuse
    - ceph-iscsi-cli
    - ceph-iscsi-config
    - ceph-iscsi-tools
    - ceph-mds
    - ceph-medic
    - ceph-radosgw
    - nfs-ganesha
    - nfs-ganesha-ceph
    - nfs-ganesha-rgw
    - ntp
    - hdparm
    - python-setuptools
    - python-pycurl

- name: install ceph-ansible
  yum: name=ceph-ansible state=present

- name: disable deprecation warnings for ceph-ansible
  lineinfile:
    path: /etc/ansible/ansible.cfg
    line: "deprecation_warnings = False"
    regexp: "^#deprecation_warnings"
    state: present

- name: pre-downloading ceph container image
  docker_image: name=registry.access.redhat.com/rhceph/rhceph-3-rhel7

...
