---

- name: pre-downloading rhcs packages
  shell: yum -y --downloadonly install {{ item }}
  args:
    warn: no
  with_items:
    - ceph-base
    - ceph-common
    - ceph-selinux
    - ceph-osd
    - ceph-mon
    - ceph-mgr
    - cephmetrics-collectors
    - ceph-fuse
    - ceph-iscsi-cli
    - ceph-iscsi-config
    - ceph-iscsi-tools
    - ceph-mds
    - ceph-medic
    - ceph-radosgw
    - nfs-ganesha
    - nfs-ganesha-ceph
    - nfs-ganesha-rgw

- name: install ceph-ansible
  yum: name=ceph-ansible state=present

- name: pre-downloading ceph container image
  docker_image: name=registry.hub.docker.com/ceph/tag-stable-3.0-luminous-centos-7

...
